version: '3.5'
services:
  server:
    container_name: sgr-api
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: gabrasgp/sgr-service:1.0.0
    ports:
      - "8083:8083"
    networks:
      - sgr_network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    restart: always
    expose:
      - "8083"
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: sgr_database
      MYSQL_TCP_PORT: 3306
    networks:
      - sgr_network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'mysql',
          '--user=root',
          '--password=senha'
        ]
      interval: 3s
      timeout: 3s
      retries: 5
networks:
  sgr_network:
    driver: bridge
